name: ${name}
version: ${version}
author: Sunshine_wzy

main: ${main}

api-version: 1.13

commands:
    SkyDream:
        aliases: [sd]
        description: Start your SkyDream journey...

depend: [SunSTCore]