name: SkyDream
version: 4.0
author: Sunshine_wzy

main: io.github.sunshinewzy.skydream.SkyDream

api-version: 1.13

commands:
    sd:
        description: Start SkyDream journey...

depend: [SunSTCore]