name: SkyDream
version: 4.1
author: Sunshine_wzy

main: io.github.sunshinewzy.skydream.SkyDream

api-version: 1.13

commands:
    SkyDream:
        aliases: [sd]
        description: Start your SkyDream journey...

depend: [SunSTCore]